x-default: &default
  restart: unless-stopped
  networks:
  - common
  env_file:
  - .env
  depends_on:
    python_base:
      condition: service_completed_successfully

x-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 30s

services:
  url_shortener_app_backend:
    <<: *default
    build: .
    ports:
    - ${APP_PORT}:${APP_PORT}
    depends_on:
      url_shortener_postgres:
        condition: service_healthy

  url_shortener_postgres:
    <<: *default
    image: postgres:${POSTGRES_VERSION}
    healthcheck:
      test: [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' || exit 1"]
      <<: *default-healthcheck
    volumes:
    - url_shortener_pg_data:/var/lib/postgresql/data
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  url_shortener_pg_data:

networks:
  common:
    name: common
